version: '3.8'

services:
  react-app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - REACT_APP_HOST_URL=http://localhost:8080
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
