version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      timeout: 20s
      retries: 10

  springbootapp:
    container_name: springbootapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_PORT=3306
      - DATABASE_NAME=users
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
    # env_file:
    #   - .env
    depends_on:
      - mysqldb

